### ISSUE TITLE
High traffic to mybinder.org

### ISSUE THREAD

**Issue by rgaiacs** [hughshanahan/CS2900-Lab-1#4]
Dear @hughshanahan,

we had a incident at the mybinder.org federation and our investigation, see https://github.com/jupyterhub/mybinder.org-deploy/issues/2922, lead to this repository.

Since the end of April 2023, mybinder.org is running under reduced capacity as announced at https://blog.jupyter.org/mybinder-org-reducing-capacity-c93ccfc6413f.

Were you teaching and using this repository today? Thanks for the help!

**Comment by hughshanahan** [comment]
Hi - aagh apologies for not replying! Yes I was running a class using this notebook. 

Hugh

**Comment by rgaiacs** [comment]
Thanks @hughshanahan for the reply. I hope that your class went well.

**Comment by hughshanahan** [comment]
Yes - it went fine. There were ~90 students using it per hour for two hours.My apologies if that was a drain on your resources. Do you mind me asking what was the problem it caused (if not just lots of instances being started?). The notebook itself is not doing any major computation (just showing students how to use NumPy).

**Comment by rgaiacs** [comment]
> Do you mind me asking what was the problem it caused (if not just lots of instances being started?).

For reasons that I don't know, a lot of builds for this repository started at the same time. We do one build per commit as the build is deterministic if the `requirements.txt` is configured properly. Once the build is complete, we launch the web service for the user. Launch is relatively cheap.

Because of the many builds at the same time, we were unable to launch new web services for new users.

**Comment by hughshanahan** [comment]
So - could it be I did something wrong on requirements.txt file?

**Comment by rgaiacs** [comment]
> could it be I did something wrong on requirements.txt file?

The `requirements.txt` is only used during the build.
